name: Docker Images

on:
  push:
    # branches:
    # - main
    # tags:
    # - v*
  pull_request:
    branches:
    - main
  schedule:
    - cron:  '1 0 * * 0'
  release:
    types: [published]
  workflow_dispatch:

jobs:
  docker:
    name: Build and publish Docker images
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Prepare
        id: prep
        run: |
          DOCKER_IMAGE=scailfin/madgraph5-amc-nlo
          VERSION=latest
          MADGRAPH_VERSION=mg5_amc3.1.0
          REPO_NAME=${{github.repository}}
          REPO_NAME_LOWERCASE="${REPO_NAME,,}"
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          elif [[ $GITHUB_REF == refs/pull/* ]]; then
            VERSION=pr-${{ github.event.number }}
          fi
          TAGS="${DOCKER_IMAGE}:${VERSION}"
          TAGS="$TAGS,${DOCKER_IMAGE}:latest,${DOCKER_IMAGE}:${MADGRAPH_VERSION},${DOCKER_IMAGE}:sha-${GITHUB_SHA::8}"
          # Releases also have GITHUB_REFs that are tags, so reuse VERSION
          if [ "${{ github.event_name }}" = "release" ]; then
            TAGS="$TAGS,${DOCKER_IMAGE}:latest-stable,ghcr.io/${REPO_NAME_LOWERCASE}:latest-stable,ghcr.io/${REPO_NAME_LOWERCASE}:${VERSION}"
          fi
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          echo ::set-output name=repo_name_lowercase::"${REPO_NAME_LOWERCASE}"
          echo ::set-output name=madgraph_version::"${MADGRAPH_VERSION}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host

      - name: Login to DockerHub
        # if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        # if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Debian base
        id: docker_build_debian_base
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/debian/Dockerfile
          build-args: BUILDER_IMAGE=python:3.8-slim
          tags: localhost:5000/madgraph5-amc-nlo-debian-base:latest
          # load: true
          push: true

      - name: List built images
        run: docker images

      - name: Test build
        id: docker_build_test
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile
          build-args: BUILDER_IMAGE=localhost:5000/madgraph5-amc-nlo-debian-base:latest
          tags: ${{ steps.prep.outputs.tags }}
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}
          load: true
          push: false

      - name: Image digest
        run: echo ${{ steps.docker_build_test.outputs.digest }}

      - name: List built images
        run: docker images

      - name: Run test program
        # Need to run not below PWD to have non-root write with GHA
        run: >-
          docker run --rm
          -v $PWD:$PWD
          scailfin/madgraph5-amc-nlo:sha-${GITHUB_SHA::8}
          "cp -r ${PWD}/tests .; cd tests; bash tests.sh"

      - name: Build and publish to registry
        # every PR will trigger a push event on main, so check the push event is actually coming from main
        # if: github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository == 'scailfin/MadGraph5_aMC-NLO'
        id: docker_build_latest
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile
          build-args: BUILDER_IMAGE=localhost:5000/madgraph5-amc-nlo-debian-base:latest
          tags: |
            scailfin/madgraph5-amc-nlo:latest
            scailfin/madgraph5-amc-nlo:${{ steps.prep.outputs.madgraph_version }}
            ghcr.io/${{ steps.prep.outputs.repo_name_lowercase }}:latest
            ghcr.io/${{ steps.prep.outputs.repo_name_lowercase }}:${{ steps.prep.outputs.madgraph_version }}
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}
          push: true

      - name: Build and publish to registry with release tag
        if: github.event_name == 'release' && github.event.action == 'published' && github.repository == 'scailfin/MadGraph5_aMC-NLO'
        id: docker_build_release
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile
          build-args: BUILDER_IMAGE=localhost:5000/madgraph5-amc-nlo-debian-base:latest
          tags: ${{ steps.prep.outputs.tags }}
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}
          push: true

  centos:
    name: Build and publish CentOS based images
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Prepare
        id: prep
        run: |
          DOCKER_IMAGE=scailfin/madgraph5-amc-nlo-centos
          VERSION=latest
          MADGRAPH_VERSION=mg5_amc3.1.0
          REPO_NAME=${{github.repository}}
          REPO_NAME_LOWERCASE="${REPO_NAME,,}"
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          elif [[ $GITHUB_REF == refs/pull/* ]]; then
            VERSION=pr-${{ github.event.number }}
          fi
          TAGS="${DOCKER_IMAGE}:${VERSION}"
          TAGS="$TAGS,${DOCKER_IMAGE}:latest,${DOCKER_IMAGE}:${MADGRAPH_VERSION},${DOCKER_IMAGE}:sha-${GITHUB_SHA::8}"
          # Releases also have GITHUB_REFs that are tags, so reuse VERSION
          if [ "${{ github.event_name }}" = "release" ]; then
            TAGS="$TAGS,${DOCKER_IMAGE}:latest-stable,ghcr.io/${REPO_NAME_LOWERCASE}:latest-stable-centos,ghcr.io/${REPO_NAME_LOWERCASE}:${VERSION}-centos"
          fi
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          echo ::set-output name=repo_name_lowercase::"${REPO_NAME_LOWERCASE}"
          echo ::set-output name=madgraph_version::"${MADGRAPH_VERSION}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build CentOS base
        id: docker_build_centos_base
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/centos/Dockerfile
          build-args: BUILDER_IMAGE=neubauergroup/centos-python3:3.8.8
          tags: localhost:5000/madgraph5-amc-nlo-centos-base:latest
          # load: true
          push: true

      - name: List built images
        run: docker images

      - name: Test build
        id: docker_build_test
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile
          build-args: BUILDER_IMAGE=localhost:5000/madgraph5-amc-nlo-centos-base:latest
          tags: ${{ steps.prep.outputs.tags }}
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}
          load: true
          push: false

      - name: Image digest
        run: echo ${{ steps.docker_build_test.outputs.digest }}

      - name: List built images
        run: docker images

      - name: Run test program
        # Need to run not below PWD to have non-root write with GHA
        run: >-
          docker run --rm
          -v $PWD:$PWD
          scailfin/madgraph5-amc-nlo-centos:sha-${GITHUB_SHA::8}
          "cp -r ${PWD}/tests .; cd tests; bash tests.sh"

      - name: Build and publish to registry
        # every PR will trigger a push event on main, so check the push event is actually coming from main
        # if: github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository == 'scailfin/MadGraph5_aMC-NLO'
        id: docker_build_latest
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile
          build-args: BUILDER_IMAGE=localhost:5000/madgraph5-amc-nlo-debian-base:latest
          tags: |
            scailfin/madgraph5-amc-nlo-centos:latest
            scailfin/madgraph5-amc-nlo-centos:${{ steps.prep.outputs.madgraph_version }}
            ghcr.io/${{ steps.prep.outputs.repo_name_lowercase }}:latest-centos
            ghcr.io/${{ steps.prep.outputs.repo_name_lowercase }}:${{ steps.prep.outputs.madgraph_version }}-centos
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}
          push: true

      - name: Build and publish to registry with release tag
        if: github.event_name == 'release' && github.event.action == 'published' && github.repository == 'scailfin/MadGraph5_aMC-NLO'
        id: docker_build_release
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile
          build-args: BUILDER_IMAGE=localhost:5000/madgraph5-amc-nlo-debian-base:latest
          tags: ${{ steps.prep.outputs.tags }}
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}
          push: true
